package my.novelreader.coreui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.luminance

@Composable
fun ColorScheme.isLightTheme() = background.luminance() > 0.5

val light_colorScheme = ColorScheme(
    primary = Grey25,
    onPrimary = Grey900,
    primaryContainer = Grey50,
    onPrimaryContainer = Grey800,
    inversePrimary = Grey900,
    secondary = Grey25,
    onSecondary = Grey900,
    secondaryContainer = AccentLight,
    onSecondaryContainer = Grey25,
    tertiary = Grey200,
    onTertiary = Grey600,
    tertiaryContainer = Grey50,
    onTertiaryContainer = Grey900,
    background = Grey25,
    onBackground = Grey900,
    surface = Grey25,
    onSurface = Grey900,
    surfaceVariant = Grey50,
    onSurfaceVariant = Grey900,
    surfaceTint = AccentLight,
    inverseSurface = Grey900,
    inverseOnSurface = Grey25,
    error = Error300,
    onError = Grey900,
    errorContainer = Error200,
    onErrorContainer = Grey800,
    outline = Grey800,
    outlineVariant = Grey200,
    scrim = Grey300,
)

val dark_colorScheme = ColorScheme(
    primary = Grey900,
    onPrimary = Grey25,
    primaryContainer = Grey800,
    onPrimaryContainer = Grey50,
    inversePrimary = Grey25,
    secondary = Grey900,
    onSecondary = Grey25,
    secondaryContainer = AccentDark,
    onSecondaryContainer = Grey75,
    tertiary = Grey700,
    onTertiary = Grey300,
    tertiaryContainer = Grey600,
    onTertiaryContainer = Grey50,
    background = Grey900,
    onBackground = Grey50,
    surface = Grey900,
    onSurface = Grey25,
    surfaceVariant = Grey900,
    onSurfaceVariant = Grey50,
    surfaceTint = AccentDark,
    inverseSurface = Grey25,
    inverseOnSurface = Grey900,
    error = Error600,
    onError = Grey25,
    errorContainer = Error800,
    onErrorContainer = Grey50,
    outline = Grey25,
    outlineVariant = Grey700,
    scrim = Grey800,
)

val black_colorScheme = ColorScheme(
    primary = Grey1000,
    onPrimary = Grey25,
    primaryContainer = Grey900,
    onPrimaryContainer = Grey100,
    inversePrimary = Grey25,
    secondary = Grey1000,
    onSecondary = Grey25,
    secondaryContainer = AccentBlack,
    onSecondaryContainer = Grey75,
    tertiary = Grey800,
    onTertiary = Grey300,
    tertiaryContainer = Grey700,
    onTertiaryContainer = Grey50,
    background = Grey1000,
    onBackground = Grey50,
    surface = Grey1000,
    onSurface = Grey25,
    surfaceVariant = Grey1000,
    onSurfaceVariant = Grey50,
    surfaceTint = AccentBlack,
    inverseSurface = Grey25,
    inverseOnSurface = Grey1000,
    error = Error600,
    onError = Grey25,
    errorContainer = Error800,
    onErrorContainer = Grey50,
    outline = Grey25,
    outlineVariant = Grey800,
    scrim = Grey900,
)

val darkTeal_colorScheme = ColorScheme(
    primary = TealDark900,
    onPrimary = Grey25,
    primaryContainer = TealDark800,
    onPrimaryContainer = Grey50,
    inversePrimary = Grey25,
    secondary = TealDark900,
    onSecondary = Grey25,
    secondaryContainer = TealMid,
    onSecondaryContainer = TealDark900,
    tertiary = TealDark700,
    onTertiary = TealLight300,
    tertiaryContainer = TealDark600,
    onTertiaryContainer = Grey50,
    background = TealDark900,
    onBackground = Grey50,
    surface = TealDark900,
    onSurface = Grey25,
    surfaceVariant = TealDark900,
    onSurfaceVariant = Grey50,
    surfaceTint = TealLight300,
    inverseSurface = Grey25,
    inverseOnSurface = TealDark900,
    error = Error600,
    onError = Grey25,
    errorContainer = Error800,
    onErrorContainer = Grey50,
    outline = Grey25,
    outlineVariant = TealDark700,
    scrim = TealDark800,
)

val sepia_colorScheme = ColorScheme(
    primary = SepiaLight,
    onPrimary = SepiaDark,
    primaryContainer = SepiaLight50,
    onPrimaryContainer = SepiaDark,
    inversePrimary = SepiaDark,
    secondary = SepiaLight,
    onSecondary = SepiaDark,
    secondaryContainer = AccentSepia,
    onSecondaryContainer = SepiaLight,
    tertiary = SepiaLight200,
    onTertiary = SepiaMedium600,
    tertiaryContainer = SepiaLight50,
    onTertiaryContainer = SepiaDark,
    background = SepiaLight,
    onBackground = SepiaDark,
    surface = SepiaLight,
    onSurface = SepiaDark,
    surfaceVariant = SepiaLight50,
    onSurfaceVariant = SepiaDark,
    surfaceTint = AccentSepia,
    inverseSurface = SepiaDark,
    inverseOnSurface = SepiaLight,
    error = Error300,
    onError = SepiaDark,
    errorContainer = Error200,
    onErrorContainer = SepiaDark200,
    outline = SepiaDark200,
    outlineVariant = SepiaLight200,
    scrim = SepiaLight300,
)
